version: '3'

services:
    app:
        image: retno/lavsms-app:latest
        container_name: app
        restart: unless-stopped
        tty: true
        depends_on:
            - cache
        networks:
            - app-network

    web_server:
        image: retno/lavsms-webserver:latest
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8002:80"
        depends_on:
            - app
        networks:
            - app-network

    cache:
        image: redis:alpine
        container_name: cache
        restart: unless-stopped
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
